/** Auto-generated by npm run sync-demo — do not edit by hand */
export const BUNDLED_DEMO_SNAPSHOTS = [
  {
    "id": "t1_omuu4gg",
    "kind": "comment",
    "title": "Comment: Low effort scam repost — giveaway link in bio",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrs2/demo_extreme_07_selling_verified_accounts_free/omuu4gg/",
    "reportCount": 1,
    "text": "Low effort scam repost — giveaway link in bio"
  },
  {
    "id": "t1_omuu44m",
    "kind": "comment",
    "title": "Comment: Second report — still spam scam free money phishing",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrpk/demo_extreme_06_exclusive_airdrop_phishing_page/omuu44m/",
    "reportCount": 1,
    "text": "Second report — still spam scam free money phishing"
  },
  {
    "id": "t1_omuu3ue",
    "kind": "comment",
    "title": "Comment: Mod here: ignore giveaway phishing spam links",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrmv/demo_extreme_05_wire_me_500_get_5000_back/omuu3ue/",
    "reportCount": 1,
    "text": "Mod here: ignore giveaway phishing spam links"
  },
  {
    "id": "t1_omuu3h1",
    "kind": "comment",
    "title": "Comment: This is clearly spam — free money scam phishing bot",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrka/demo_extreme_04_i_hacked_the_system_free_money/omuu3h1/",
    "reportCount": 1,
    "text": "This is clearly spam — free money scam phishing bot"
  },
  {
    "id": "t1_omuu36b",
    "kind": "comment",
    "title": "Comment: Verified vendor!!! scam spam phishing giveaway DM now",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrhx/demo_extreme_03_official_mod_giveaway_claim_free/omuu36b/",
    "reportCount": 1,
    "text": "Verified vendor!!! scam spam phishing giveaway DM now"
  },
  {
    "id": "t1_omuu2s6",
    "kind": "comment",
    "title": "Comment: phishing giveaway free money spam — click my profile",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikreu/demo_extreme_02_double_your_crypto_overnight/omuu2s6/",
    "reportCount": 1,
    "text": "phishing giveaway free money spam — click my profile"
  },
  {
    "id": "t1_omuu2fg",
    "kind": "comment",
    "title": "Comment: DM me for free crypto giveaway — scam link inside",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrbw/demo_extreme_01_urgent_free_money_wire_transfer/omuu2fg/",
    "reportCount": 1,
    "text": "DM me for free crypto giveaway — scam link inside"
  },
  {
    "id": "t3_1tiksqh",
    "kind": "post",
    "title": "[DEMO LOW 05] Meta: should we run a monthly feedback post?",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksqh/demo_low_05_meta_should_we_run_a_monthly_feedback/",
    "reportCount": 1,
    "text": "[DEMO LOW 05] Meta: should we run a monthly feedback post?\nMeta: should we run a monthly feedback post?"
  },
  {
    "id": "t3_1tiksp7",
    "kind": "post",
    "title": "[DEMO LOW 04] Thanks to mods for last week cleanup thread.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksp7/demo_low_04_thanks_to_mods_for_last_week_cleanup/",
    "reportCount": 1,
    "text": "[DEMO LOW 04] Thanks to mods for last week cleanup thread.\nThanks to mods for last week cleanup thread."
  },
  {
    "id": "t3_1tiksnv",
    "kind": "post",
    "title": "[DEMO LOW 03] Looking for book recommendations from regulars.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksnv/demo_low_03_looking_for_book_recommendations_from/",
    "reportCount": 1,
    "text": "[DEMO LOW 03] Looking for book recommendations from regulars.\nLooking for book recommendations from regulars."
  },
  {
    "id": "t3_1tiksmb",
    "kind": "post",
    "title": "[DEMO LOW 02] Reminder: read the sidebar before posting.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksmb/demo_low_02_reminder_read_the_sidebar_before/",
    "reportCount": 1,
    "text": "[DEMO LOW 02] Reminder: read the sidebar before posting.\nReminder: read the sidebar before posting."
  },
  {
    "id": "t3_1tiksl3",
    "kind": "post",
    "title": "[DEMO LOW 01] Weekly community check-in — how is everyone doing?",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksl3/demo_low_01_weekly_community_checkin_how_is/",
    "reportCount": 1,
    "text": "[DEMO LOW 01] Weekly community check-in — how is everyone doing?\nWeekly community check-in — how is everyone doing?"
  },
  {
    "id": "t3_1tiksjk",
    "kind": "post",
    "title": "[DEMO MED 05] Off-topic rant — not sure which rule applies.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksjk/demo_med_05_offtopic_rant_not_sure_which_rule/",
    "reportCount": 1,
    "text": "[DEMO MED 05] Off-topic rant — not sure which rule applies.\nOff-topic rant — not sure which rule applies."
  },
  {
    "id": "t3_1tikshx",
    "kind": "post",
    "title": "[DEMO MED 04] Duplicate post from same user — is this spam or just eager?",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikshx/demo_med_04_duplicate_post_from_same_user_is_this/",
    "reportCount": 1,
    "text": "[DEMO MED 04] Duplicate post from same user — is this spam or just eager?\nDuplicate post from same user — is this spam or just eager?"
  },
  {
    "id": "t3_1tiksgc",
    "kind": "post",
    "title": "[DEMO MED 03] Possible rule break but could be innocent. Community input welcome.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksgc/demo_med_03_possible_rule_break_but_could_be/",
    "reportCount": 1,
    "text": "[DEMO MED 03] Possible rule break but could be innocent. Community input welcome.\nPossible rule break but could be innocent. Community input welcome."
  },
  {
    "id": "t3_1tiksey",
    "kind": "post",
    "title": "[DEMO MED 02] Heated argument in comments; might need review. No scam keywords here.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksey/demo_med_02_heated_argument_in_comments_might/",
    "reportCount": 1,
    "text": "[DEMO MED 02] Heated argument in comments; might need review. No scam keywords here.\nHeated argument in comments; might need review. No scam keywords here."
  },
  {
    "id": "t3_1tiksdh",
    "kind": "post",
    "title": "[DEMO MED 01] Not sure if vendor posts are allowed — posting anyway for feedback.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksdh/demo_med_01_not_sure_if_vendor_posts_are_allowed/",
    "reportCount": 1,
    "text": "[DEMO MED 01] Not sure if vendor posts are allowed — posting anyway for feedback.\nNot sure if vendor posts are allowed — posting anyway for feedback."
  },
  {
    "id": "t3_1tiksbg",
    "kind": "post",
    "title": "[DEMO HIGH 07] Bot comment flood on pinned thread — spam accounts pushing scam links.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiksbg/demo_high_07_bot_comment_flood_on_pinned_thread/",
    "reportCount": 1,
    "text": "[DEMO HIGH 07] Bot comment flood on pinned thread — spam accounts pushing scam links.\nBot comment flood on pinned thread — spam accounts pushing scam links."
  },
  {
    "id": "t3_1tiks98",
    "kind": "post",
    "title": "[DEMO HIGH 06] Raid incoming? Multiple giveaway scam posts in last hour. spam spam spam…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiks98/demo_high_06_raid_incoming_multiple_giveaway_scam/",
    "reportCount": 1,
    "text": "[DEMO HIGH 06] Raid incoming? Multiple giveaway scam posts in last hour. spam spam spam…\nRaid incoming? Multiple giveaway scam posts in last hour. spam spam spam."
  },
  {
    "id": "t3_1tiks6w",
    "kind": "post",
    "title": "[DEMO HIGH 05] Fake support rep asking for login. Smells like phishing scam spam.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiks6w/demo_high_05_fake_support_rep_asking_for_login/",
    "reportCount": 1,
    "text": "[DEMO HIGH 05] Fake support rep asking for login. Smells like phishing scam spam.\nFake support rep asking for login. Smells like phishing scam spam."
  },
  {
    "id": "t3_1tiks2i",
    "kind": "post",
    "title": "[DEMO HIGH 04] New account posting affiliate spam every hour. Possible scam funnel.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiks2i/demo_high_04_new_account_posting_affiliate_spam/",
    "reportCount": 1,
    "text": "[DEMO HIGH 04] New account posting affiliate spam every hour. Possible scam funnel.\nNew account posting affiliate spam every hour. Possible scam funnel."
  },
  {
    "id": "t3_1tiks0f",
    "kind": "post",
    "title": "[DEMO HIGH 03] Crossposting alleged giveaway — could be scam. Report if spam.",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tiks0f/demo_high_03_crossposting_alleged_giveaway_could/",
    "reportCount": 1,
    "text": "[DEMO HIGH 03] Crossposting alleged giveaway — could be scam. Report if spam.\nCrossposting alleged giveaway — could be scam. Report if spam."
  },
  {
    "id": "t3_1tikryt",
    "kind": "post",
    "title": "[DEMO HIGH 02] Is this phishing link legit? Someone sent free money offer in modmail. L…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikryt/demo_high_02_is_this_phishing_link_legit_someone/",
    "reportCount": 1,
    "text": "[DEMO HIGH 02] Is this phishing link legit? Someone sent free money offer in modmail. L…\nIs this phishing link legit? Someone sent free money offer in modmail. Looks like spam."
  },
  {
    "id": "t3_1tikrx6",
    "kind": "post",
    "title": "[DEMO HIGH 01] Suspicious vendor — DM for deals. Might be scam or spam, not sure about …",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrx6/demo_high_01_suspicious_vendor_dm_for_deals_might/",
    "reportCount": 1,
    "text": "[DEMO HIGH 01] Suspicious vendor — DM for deals. Might be scam or spam, not sure about …\nSuspicious vendor — DM for deals. Might be scam or spam, not sure about giveaway rules."
  },
  {
    "id": "t3_1tikrud",
    "kind": "post",
    "title": "[DEMO EXTREME 08] Mod team approved giveaway!!! free money scam phishing — spam repost bot…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrud/demo_extreme_08_mod_team_approved_giveaway_free/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 08] Mod team approved giveaway!!! free money scam phishing — spam repost bot…\nMod team approved giveaway!!! free money scam phishing — spam repost bot network link."
  },
  {
    "id": "t3_1tikrs2",
    "kind": "post",
    "title": "[DEMO EXTREME 07] Selling verified accounts + free money method. scam phishing spam giveaw…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrs2/demo_extreme_07_selling_verified_accounts_free/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 07] Selling verified accounts + free money method. scam phishing spam giveaw…\nSelling verified accounts + free money method. scam phishing spam giveaway bulk DM list."
  },
  {
    "id": "t3_1tikrpk",
    "kind": "post",
    "title": "[DEMO EXTREME 06] Exclusive airdrop phishing page — free money scam spam. Click giveaway l…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrpk/demo_extreme_06_exclusive_airdrop_phishing_page/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 06] Exclusive airdrop phishing page — free money scam spam. Click giveaway l…\nExclusive airdrop phishing page — free money scam spam. Click giveaway link before removal!!!"
  },
  {
    "id": "t3_1tikrmv",
    "kind": "post",
    "title": "[DEMO EXTREME 05] Wire me $500 get $5000 back guaranteed. phishing scam free money spam gi…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrmv/demo_extreme_05_wire_me_500_get_5000_back/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 05] Wire me $500 get $5000 back guaranteed. phishing scam free money spam gi…\nWire me $500 get $5000 back guaranteed. phishing scam free money spam giveaway crypto pump."
  },
  {
    "id": "t3_1tikrka",
    "kind": "post",
    "title": "[DEMO EXTREME 04] I hacked the system — free money for first 50 replies. scam phishing giv…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrka/demo_extreme_04_i_hacked_the_system_free_money/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 04] I hacked the system — free money for first 50 replies. scam phishing giv…\nI hacked the system — free money for first 50 replies. scam phishing giveaway spam bot farm."
  },
  {
    "id": "t3_1tikrhx",
    "kind": "post",
    "title": "[DEMO EXTREME 03] Official mod giveaway — claim free money now. scam phishing spam link in…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrhx/demo_extreme_03_official_mod_giveaway_claim_free/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 03] Official mod giveaway — claim free money now. scam phishing spam link in…\nOfficial mod giveaway — claim free money now. scam phishing spam link inside. Limited slots!!!"
  },
  {
    "id": "t3_1tikreu",
    "kind": "post",
    "title": "[DEMO EXTREME 02] Double your crypto overnight!!! phishing giveaway free money scam. DM fo…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikreu/demo_extreme_02_double_your_crypto_overnight/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 02] Double your crypto overnight!!! phishing giveaway free money scam. DM fo…\nDouble your crypto overnight!!! phishing giveaway free money scam. DM for wallet drain spam."
  },
  {
    "id": "t3_1tikrbw",
    "kind": "post",
    "title": "[DEMO EXTREME 01] URGENT: free money wire transfer. phishing scam giveaway link — act befo…",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tikrbw/demo_extreme_01_urgent_free_money_wire_transfer/",
    "reportCount": 1,
    "text": "[DEMO EXTREME 01] URGENT: free money wire transfer. phishing scam giveaway link — act befo…\nURGENT: free money wire transfer. phishing scam giveaway link — act before ban. spam spam scam."
  },
  {
    "id": "t1_olwshdq",
    "kind": "comment",
    "title": "Comment: DM me for free crypto giveaway — scam link inside",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tdphku/demo_high_free_money_crypto_scam_act_now/olwshdq/",
    "reportCount": 1,
    "text": "DM me for free crypto giveaway — scam link inside"
  },
  {
    "id": "t3_1tdphl7",
    "kind": "post",
    "title": "[DEMO MED] Suspicious vendor DM me for deals",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tdphl7/demo_med_suspicious_vendor_dm_me_for_deals/",
    "reportCount": 1,
    "text": "[DEMO MED] Suspicious vendor DM me for deals\nNot sure if this is allowed but posting anyway."
  }
] as const;
