/** Auto-generated by npm run sync-demo — do not edit by hand */
export const BUNDLED_DEMO_SNAPSHOTS = [
  {
    "id": "t1_olwyqsa",
    "kind": "comment",
    "title": "Comment: DM me for free crypto giveaway — scam link inside",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tdqiiw/demo_high_free_money_crypto_scam_act_now/olwyqsa/",
    "reportCount": 1,
    "text": "DM me for free crypto giveaway — scam link inside"
  },
  {
    "id": "t3_1tdqijg",
    "kind": "post",
    "title": "[DEMO LOW] Weekly community check-in thread",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tdqijg/demo_low_weekly_community_checkin_thread/",
    "reportCount": 1,
    "text": "[DEMO LOW] Weekly community check-in thread\nHow is everyone doing this week? Share updates."
  },
  {
    "id": "t3_1tdqij7",
    "kind": "post",
    "title": "[DEMO MED] Suspicious vendor DM me for deals",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tdqij7/demo_med_suspicious_vendor_dm_me_for_deals/",
    "reportCount": 1,
    "text": "[DEMO MED] Suspicious vendor DM me for deals\nNot sure if this is allowed but posting anyway."
  },
  {
    "id": "t3_1tdqiiw",
    "kind": "post",
    "title": "[DEMO HIGH] Free money crypto scam — act now!!!",
    "authorName": "u/Crafty_Cell_8766",
    "permalink": "https://www.reddit.com/r/queue_toolk_dev/comments/1tdqiiw/demo_high_free_money_crypto_scam_act_now/",
    "reportCount": 1,
    "text": "[DEMO HIGH] Free money crypto scam — act now!!!\nLimited giveaway phishing link. scam spam free money."
  }
] as const;
